"""Remove is_acrive field

Revision ID: 1d3bb02774e2
Revises: 80e488124efb
Create Date: 2024-12-02 15:21:56.535890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3bb02774e2'
down_revision = '80e488124efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_acrive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_acrive', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
