"""Remove autor field

Revision ID: ad21f2251da6
Revises: 93fa17dfdcfe
Create Date: 2024-12-02 15:25:23.232664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad21f2251da6'
down_revision = '93fa17dfdcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=30), nullable=True))
        batch_op.drop_column('autor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
